apiVersion: v1
kind: Service
metadata:
  name: imessage-proxysync
  namespace: matrix
  labels:
    app: imessage-proxysync
spec:
  type: ClusterIP
  selector:
    app: imessage-proxysync
  ports:
    - name: http
      port: 29332
      protocol: TCP
      targetPort: 29332
