apiVersion: v1
kind: Service
metadata:
  name: discord-service
  namespace: matrix
  labels:
    app: discord
spec:
  type: ClusterIP
  selector:
    app: discord
  ports:
    - name: http
      port: 29334
      protocol: TCP
      targetPort: 29334
