apiVersion: v1
kind: ConfigMap
metadata:
  name: element-config
  namespace: matrix
data:
  config.json: |
    {
      "default_server_config": {
        "m.homeserver": {
          "base_url": "https://ryleycoyote.com",
          "server_name": "ryleycoyote.com"
        },
        "m.identity_server": {
          "base_url": "https://vector.im"
        }
      },
      "disable_custom_urls": false,
      "disable_guests": true,
      "disable_login_language_selector": false,
      "disable_3pid_login": false,
      "brand": "Element",
      "integrations_ui_url": "https://scalar.vector.im/",
      "integrations_rest_url": "https://scalar.vector.im/api",
      "integrations_widgets_urls": [
          "https://scalar.vector.im/_matrix/integrations/v1",
          "https://scalar.vector.im/api",
          "https://scalar-staging.vector.im/_matrix/integrations/v1",
          "https://scalar-staging.vector.im/api",
          "https://scalar-staging.riot.im/scalar/api"
      ],
      "bug_report_endpoint_url": "https://element.io/bugreports/submit",
      "defaultCountryCode": "US",
      "show_labs_settings": true,
      "features": { },
      "default_federate": true,
      "default_theme": "dark",
      "room_directory": {
        "servers": [ "ryleycoyote.com" ]
      },
      "enable_presence_by_hs_url": {
        "https://matrix.org": false,
        "https://matrix-client.matrix.org": false
      },
      "setting_defaults": {
        "breadcrumbs": true
      },
      "jitsi": {
        "preferred_domain": "meet.element.io"
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: element
  namespace: matrix
spec:
  selector:
    matchLabels:
      app: element
  replicas: 1
  template:
    metadata:
      labels:
        app: element
    spec:
      containers:
        - name: element
          image: vectorim/element-web:latest
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.json
              subPath: config.json
          ports:
            - containerPort: 80
              name: element
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: element
            initialDelaySeconds: 2
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /
              port: element
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: config-volume
          configMap:
            name: element-config
---
apiVersion: v1
kind: Service
metadata:
  name: element
  namespace: matrix
spec:
  selector:
    app: element
  ports:
    - name: default
      protocol: TCP
      port: 80
      targetPort: 80
