apiVersion: v1
kind: PersistentVolume
metadata:
  name: synapse-pv
  namespace: matrix
  labels:
    pvc_type: synapse-pv
spec:
  storageClassName: local-path
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /etc/matrix/synapse/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synapse-pv-claim
  namespace: matrix
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  #  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapse
  namespace: matrix
spec:
  selector:
    matchLabels:
      app: synapse
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: synapse
    spec:
      containers:
        - image: matrixdotorg/synapse:v1.97.0
          name: synapse
          # args: ["generate"]
          # env:
          #   - name: SYNAPSE_SERVER_NAME
          #     value: "ryleycoyote.com"
          #   - name: SYNAPSE_REPORT_STATS
          #     value: "no"
          volumeMounts:
            - name: data
              mountPath: /data
          ports:
            - containerPort: 8008
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: synapse-pv-claim
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.43.0.10
          - 8.8.8.8
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: synapse
  name: synapse-service
  namespace: matrix
spec:
  clusterIP: None
  ports:
    - name: http
      port: 8008
      protocol: TCP
      targetPort: 8008
  selector:
    app: synapse
  type: ClusterIP
