apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: overseerr-statefulset
  namespace: plex
  labels:
    app: overseerr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: overseerr
  serviceName: overseerr-svc
  template:
    metadata:
      labels:
        app: overseerr
    spec:
      containers:
        - name: overseerr
          image: sctx/overseerr
          resources:
            requests:
              memory: "200Mi"
              cpu: "50m"
            limits:
              memory: "400Mi"
              cpu: "200m"
          ports:
            - containerPort: 5055
          volumeMounts:
            - mountPath: "/app/config"
              name: overseerr-pvc
          env:
            - name: LOG_LEVEL
              value: "debug"
            - name: PORT
              value: "5055"
            - name: TZ
              value: "America/Chicago"
  volumeClaimTemplates:
    - metadata:
        name: overseerr-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: local-path
---
apiVersion: v1
kind: Service
metadata:
  name: overseerr-svc
  namespace: plex
  labels:
    app: overseerr
spec:
  type: ClusterIP
  selector:
    app: overseerr
  ports:
    - port: 80
      targetPort: 5055
      protocol: TCP
