# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: udp-services
#   namespace: nginx-ingress
# data:
#   8766: "dev/forest-svc:8766"
#   27016: "dev/forest-svc:27016"
#   9700: "dev/forest-svc:9700"
# ---
# apiVersion: k8s.nginx.org/v1alpha1
# kind: GlobalConfiguration
# metadata:
#   name: nginx-configuration
#   namespace: nginx-ingress
# spec:
#   listeners:
#     - name: port1-udp
#       port: 8766
#       protocol: UDP
#     - name: port2-udp
#       port: 27016
#       protocol: UDP
#     - name: port3-udp
#       port: 9700
#       protocol: UDP
# ---
# apiVersion: k8s.nginx.org/v1alpha1
# kind: TransportServer
# metadata:
#   name: forest-svc-listener1
#   namespace: dev
# spec:
#   listener:
#     name: port1-udp
#     protocol: UDP
#   upstreams:
#     - name: forest1-listener-upstream
#       service: forest-svc
#       port: 8766
#   # upstreamParameters:
#   #   udpRequests: 1
#   action:
#     pass: forest1-listener-upstream
