apiVersion: v1
kind: Namespace
metadata:
  name: tautulli
  labels:
    name: tautulli
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tautulli-statefulset
  namespace: tautulli
  labels:
    app: tautulli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tautulli
  template:
    metadata:
      labels:
        app: tautulli
    spec:
      containers:
      - name: tautulli
        image: ghcr.io/tautulli/tautulli
        ports:
        - containerPort: 8181
        volumeMounts:
        - mountPath: "/config"
          name: tautulli-pvc
        env:
          - name: LOG_LEVEL
            value: "debug"
          - name: PUID
            value: "1001"
          - name: PGID
            value: "1001"
          - name: TZ
            value: "America/Chicago"
  volumeClaimTemplates:
  - metadata:
      name: tautulli-pvc
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: do-block-storage
---
apiVersion: v1
kind: Service
metadata:
  name: tautulli-service
  namespace: tautulli
  labels:
    app: tautulli
spec:
  type: ClusterIP
  selector:
    app: tautulli
  ports:
  - port: 80
    targetPort: 8181
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tautulli-ingress
  namespace: tautulli
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
      - dashboard.freeceweed.com
      secretName: letsencrypt-prod
  rules:
    - host: dashboard.freeceweed.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tautulli-service
                port:
                  number: 80