apiVersion: v1
kind: Service
metadata:
  labels:
    app: abiotic
  name: abiotic-game-port
  namespace: factor
spec:
  type: NodePort
  ports:
    - name: game
      port: 7777
      targetPort: 7777
      protocol: UDP
      nodePort: 30177
    - name: query
      port: 27015
      targetPort: 27015
      protocol: UDP
      nodePort: 30178
  selector:
    app: abiotic
